# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/inhere',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/inhere',
                'lib_path': 'inhere'},
  'syms': { 'inhere.core': {},
            'inhere.gptanalysis': { 'inhere.gptanalysis.format_examples': ('gptanalysis.html#format_examples', 'inhere/gptanalysis.py'),
                                    'inhere.gptanalysis.get_examples': ('gptanalysis.html#get_examples', 'inhere/gptanalysis.py')},
            'inhere.src': { 'inhere.src.get_cluster_distances': ('src.html#get_cluster_distances', 'inhere/src.py'),
                            'inhere.src.get_number_of_clusters': ('src.html#get_number_of_clusters', 'inhere/src.py'),
                            'inhere.src.get_one_hot_encoding': ('src.html#get_one_hot_encoding', 'inhere/src.py'),
                            'inhere.src.load_data': ('src.html#load_data', 'inhere/src.py'),
                            'inhere.src.make_elbow_chart': ('src.html#make_elbow_chart', 'inhere/src.py'),
                            'inhere.src.plot_tsne': ('src.html#plot_tsne', 'inhere/src.py'),
                            'inhere.src.reduce_dimensions': ('src.html#reduce_dimensions', 'inhere/src.py'),
                            'inhere.src.run_clustering': ('src.html#run_clustering', 'inhere/src.py'),
                            'inhere.src.run_tsne': ('src.html#run_tsne', 'inhere/src.py')}}}
