# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/inhere',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/inhere',
                'lib_path': 'inhere'},
  'syms': {'inhere.core': {'inhere.core.foo': ('core.html#foo', 'inhere/core.py')}}}
