# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_gptanalysis.ipynb.

# %% auto 0
__all__ = ['get_examples', 'format_examples']

# %% ../nbs/02_gptanalysis.ipynb 10
def get_examples(df, cluster, n):
	return (df
		.nsmallest(n, f'dist_cluster_{cluster}')
		.assign(text = lambda row: row['left_context'] + ' ' + row['node'] + ' ' + row['right_context'])
		.loc[:, ['text']]
	)

# %% ../nbs/02_gptanalysis.ipynb 12
def format_examples(examples):
	# convert to list of strings
	examples = examples['text'].tolist()
	# join all examples into one string with linebreaks
	examples = '- ' + '\n- '.join(examples)
	return examples
